# Home Manager module: btop
# Source-filter (exclude generated theme file) + generated catppuccin.theme from nix/colors.nix
# btop.conf stays as raw source (just references theme by name)
{
  config,
  lib,
  pkgs,
  colors,
  ...
}: let
  h = colors.withHash;
  a = colors.accent.normal;
  s = colors.structural;
  bg = colors.background.override;

  # Filter out the generated theme file from source tree
  btopSource = lib.cleanSourceWith {
    src = ../../configs/btop;
    filter = path: _type:
      !(lib.hasSuffix "/themes/catppuccin.theme" path);
  };
in {
  # Deploy btop.conf + themes/catppuccin.theme.bak as raw source
  xdg.configFile."btop" = {
    source = btopSource;
    recursive = true;
  };

  # Generated catppuccin.theme — colors from nix/colors.nix (normal tier)
  xdg.configFile."btop/themes/catppuccin.theme".text = ''
    # Generated by Nix from nix/colors.nix
    # Normal tier colorscheme
    # See docs/colorscheme.md for reference

    # Main background, empty for terminal default, need to be empty if you want transparent background
    theme[main_bg]="${h bg.base}"

    # Main text color (fg)
    theme[main_fg]="${h s.fg}"

    # Title color for boxes (fg)
    theme[title]="${h s.fg}"

    # Highlight color for keyboard shortcuts (blue)
    theme[hi_fg]="${h a.blue}"

    # Background color of selected item in processes box (surface-sunken)
    theme[selected_bg]="${h s.surface-sunken}"

    # Foreground color of selected item in processes box (blue)
    theme[selected_fg]="${h a.blue}"

    # Color of inactive/disabled text (border-muted)
    theme[inactive_fg]="${h s.border-muted}"

    # Color of text appearing on top of graphs, i.e uptime and current network graph scaling (coral)
    theme[graph_text]="${h a.coral}"

    # Background color of the percentage meters
    theme[meter_bg]="#282828"

    # Misc colors for processes box including mini cpu graphs, details memory graph and details status text (coral)
    theme[proc_misc]="${h a.coral}"

    # CPU, Memory, Network, Proc box outline colors
    theme[cpu_box]="${h a.purple}"
    theme[mem_box]="${h a.green}"
    theme[net_box]="${h a.blue}"
    theme[proc_box]="${h a.orange}"

    # Box divider line and small boxes line color (border-muted)
    theme[div_line]="${h s.border-muted}"

    # Temperature graph color (Green -> Yellow -> Red)
    theme[temp_start]="${h a.green}"
    theme[temp_mid]="${h a.yellow}"
    theme[temp_end]="${h a.red}"

    # CPU graph colors (Teal -> Azure -> Lilac)
    theme[cpu_start]="${h a.teal}"
    theme[cpu_mid]="${h a.azure}"
    theme[cpu_end]="${h a.lilac}"

    # Mem/Disk free meter (Purple -> Lilac -> Blue)
    theme[free_start]="${h a.purple}"
    theme[free_mid]="${h a.lilac}"
    theme[free_end]="${h a.blue}"

    # Mem/Disk cached meter (Azure -> Blue -> Lilac)
    theme[cached_start]="${h a.azure}"
    theme[cached_mid]="${h a.blue}"
    theme[cached_end]="${h a.lilac}"

    # Mem/Disk available meter (Orange -> Red-soft -> Red)
    theme[available_start]="${h a.orange}"
    theme[available_mid]="${h a.red-soft}"
    theme[available_end]="${h a.red}"

    # Mem/Disk used meter (Green -> Teal -> Cyan)
    theme[used_start]="${h a.green}"
    theme[used_mid]="${h a.teal}"
    theme[used_end]="${h a.cyan}"

    # Download graph colors (Orange -> Red-soft -> Red)
    theme[download_start]="${h a.orange}"
    theme[download_mid]="${h a.red-soft}"
    theme[download_end]="${h a.red}"

    # Upload graph colors (Green -> Teal -> Cyan)
    theme[upload_start]="${h a.green}"
    theme[upload_mid]="${h a.teal}"
    theme[upload_end]="${h a.cyan}"

    # Process box color gradient for threads, mem and cpu usage (Azure -> Lilac -> Purple)
    theme[process_start]="${h a.azure}"
    theme[process_mid]="${h a.lilac}"
    theme[process_end]="${h a.purple}"
  '';
}
