# Home Manager module: Ghostty terminal
# Generated config + theme file (colors from nix/colors.nix)
# Raw source for shaders and icns

{ config, lib, pkgs, colors, ... }:

let
  h = colors.withHash;
  a = colors.accent;
  s = colors.structural;
  bg = colors.background.catppuccin;
  o = colors.opacity;
in {
  # Generated main config
  xdg.configFile."ghostty/config".text = ''
    # Documentation:  https://ghostty.org/docs/config

    # --- SHELL ---
    shell-integration-features = ssh-env, no-cursor, sudo, ssh-terminfo
    command = "/usr/local/bin/nushell --login"

    # --- TEXT ---
    font-family = "JetBrainsMono Nerd Font Mono"
    font-size = 17
    font-feature = +liga
    font-thicken = true
    link-url = true

    # --- WINDOW ---
    macos-titlebar-style = hidden
    macos-titlebar-proxy-icon = hidden
    macos-window-buttons = hidden
    background-opacity = ${toString o.background}
    background-blur = true
    window-padding-balance = true

    # --- COLORS ---
    theme = colorscheme-normal
    cursor-color = ${h colors.derived.cursor}
    cursor-text = ${h colors.background.override.base}
    bold-color = bright

    # --- CURSOR ---
    adjust-cursor-thickness = +6
    adjust-cursor-height = -4
    cursor-opacity = ${toString o.cursor}
    cursor-style-blink = false
    cursor-style = block
    mouse-hide-while-typing = true
    custom-shader = shaders/cursor_trail.glsl
    custom-shader-animation = always

    # --- BELL & NOTIFICATIONS ---
    bell-features = system, attention, no-title, no-audio, no-border
    desktop-notifications = true
    app-notifications = config-reload, clipboard-copy

    # --- QUIT BEHAVIOR ---
    confirm-close-surface = false
    quit-after-last-window-closed = true

    # --- CLIPBOARD BEHAVIOR ---
    clipboard-read = allow
    clipboard-write = allow
    keybind = shift+enter=text:\x1b\r
    clipboard-trim-trailing-spaces = true

    # --- APP ICON ---
    macos-icon = custom

    # --- QUICK TERMINAL ---
    keybind = super+e=toggle_quick_terminal
    quick-terminal-position = center
    quick-terminal-size = 60%,80%
    quick-terminal-autohide = true
    quick-terminal-animation-duration = 0.01
  '';

  # Generated theme file — ANSI palette from accent tiers
  # 0-7: normal tier, 8-15: bright tier
  xdg.configFile."ghostty/themes/colorscheme-normal".text = ''
    # Generated by Nix from nix/colors.nix
    # ANSI palette: normal tier for 0-7, bright tier for 8-15

    background = ${h bg.base}
    foreground = ${h s.fg}
    cursor-color = ${h colors.derived.cursor}
    cursor-text = ${h colors.background.override.base}
    selection-background = ${h s.surface}
    selection-foreground = ${h s.fg}

    palette = 0=${h s.surface-sunken}
    palette = 1=${h a.normal.red}
    palette = 2=${h a.normal.green}
    palette = 3=${h a.normal.yellow}
    palette = 4=${h a.normal.blue}
    palette = 5=${h a.normal.pink}
    palette = 6=${h a.normal.teal}
    palette = 7=${h s.fg}
    palette = 8=${h s.surface}
    palette = 9=${h a.bright.red}
    palette = 10=${h a.bright.green}
    palette = 11=${h a.bright.yellow}
    palette = 12=${h a.bright.blue}
    palette = 13=${h a.bright.pink}
    palette = 14=${h a.bright.teal}
    palette = 15=${h s.fg-secondary}
  '';

  # Raw source: shaders
  xdg.configFile."ghostty/shaders" = {
    source = ../../ghostty.pkd/.config/ghostty/shaders;
    recursive = true;
  };

  # Raw source: app icon
  xdg.configFile."ghostty/Ghostty.icns".source = ../../ghostty.pkd/.config/ghostty/Ghostty.icns;
}
