# Home Manager module: Neovim
# Deploys entire nvim config from source, generates palette.lua from nix/colors.nix
# Source-filter excludes the generated palette.lua path to avoid conflicts
{
  config,
  lib,
  pkgs,
  colors,
  ...
}: let
  h = colors.withHash;
  a = colors.accent;
  s = colors.structural;
  bg = colors.background.override;

  # Filter out the generated palette.lua from the source tree
  nvimSource = lib.cleanSourceWith {
    src = ../../configs/neovim;
    filter = path: _type:
      !(lib.hasSuffix "/lua/colorscheme/palette.lua" path);
  };
in {
  programs.neovim = {
    enable = true;
    vimAlias = false;
    defaultEditor = true;
    withRuby = false;
    withPython3 = false;
  };

  # Deploy entire nvim tree EXCEPT the generated palette file
  xdg.configFile."nvim" = {
    source = nvimSource;
    recursive = true;
  };

  # Generated palette module — required by theme.lua and lualine.lua
  xdg.configFile."nvim/lua/colorscheme/palette.lua".text = ''
    -- Generated by Nix from nix/colors.nix
    -- Do not edit — changes will be overwritten
    -- See docs/colorscheme.md for reference

    local M = {}

    M.accent = {
      dimmed = {
        coral    = "${h a.dimmed.coral}",
        salmon   = "${h a.dimmed.salmon}",
        pink     = "${h a.dimmed.pink}",
        purple   = "${h a.dimmed.purple}",
        red      = "${h a.dimmed.red}",
        ["red-soft"] = "${h a.dimmed.red-soft}",
        orange   = "${h a.dimmed.orange}",
        yellow   = "${h a.dimmed.yellow}",
        green    = "${h a.dimmed.green}",
        teal     = "${h a.dimmed.teal}",
        cyan     = "${h a.dimmed.cyan}",
        azure    = "${h a.dimmed.azure}",
        blue     = "${h a.dimmed.blue}",
        lilac    = "${h a.dimmed.lilac}",
      },
      normal = {
        coral    = "${h a.normal.coral}",
        salmon   = "${h a.normal.salmon}",
        pink     = "${h a.normal.pink}",
        purple   = "${h a.normal.purple}",
        red      = "${h a.normal.red}",
        ["red-soft"] = "${h a.normal.red-soft}",
        orange   = "${h a.normal.orange}",
        yellow   = "${h a.normal.yellow}",
        green    = "${h a.normal.green}",
        teal     = "${h a.normal.teal}",
        cyan     = "${h a.normal.cyan}",
        azure    = "${h a.normal.azure}",
        blue     = "${h a.normal.blue}",
        lilac    = "${h a.normal.lilac}",
      },
      bright = {
        coral    = "${h a.bright.coral}",
        salmon   = "${h a.bright.salmon}",
        pink     = "${h a.bright.pink}",
        purple   = "${h a.bright.purple}",
        red      = "${h a.bright.red}",
        ["red-soft"] = "${h a.bright.red-soft}",
        orange   = "${h a.bright.orange}",
        yellow   = "${h a.bright.yellow}",
        green    = "${h a.bright.green}",
        teal     = "${h a.bright.teal}",
        cyan     = "${h a.bright.cyan}",
        azure    = "${h a.bright.azure}",
        blue     = "${h a.bright.blue}",
        lilac    = "${h a.bright.lilac}",
      },
    }

    M.structural = {
      fg             = "${h s.fg}",
      ["fg-secondary"]   = "${h s.fg-secondary}",
      ["fg-muted"]       = "${h s.fg-muted}",
      ["fg-faint"]       = "${h s.fg-faint}",
      border         = "${h s.border}",
      ["border-muted"]   = "${h s.border-muted}",
      ["surface-raised"] = "${h s.surface-raised}",
      surface        = "${h s.surface}",
      ["surface-sunken"] = "${h s.surface-sunken}",
    }

    M.background = {
      bg           = "${h bg.base}",
      ["bg-secondary"] = "${h bg.mantle}",
      ["bg-deep"]      = "${h bg.crust}",
    }

    return M
  '';
}
