# Home Manager module: Nushell
# Deploys entire nushell config from source, generates colors.nu from nix/colors.nix
# Source-filter excludes the generated colors.nu path to avoid conflicts
# Shell integrations (starship/zoxide/carapace) handled manually in env.nu
# because source-deployed nushell config overrides HM's extraConfig injection

{ config, lib, pkgs, colors, ... }:

let
  h = colors.withHash;
  a = colors.accent.normal;
  s = colors.structural;
  bg = colors.background.override;

  # Filter out the generated colors.nu from the source tree
  nushellSource = lib.cleanSourceWith {
    src = ../../nushell.pkd/.config/nushell;
    filter = path: _type:
      !(lib.hasSuffix "/confs/colors.nu" path);
  };
in {
  programs.nushell = {
    enable = true;
  };

  # Shell integrations handled manually in env.nu (cache file approach)
  # HM's enableNushellIntegration doesn't work with source-deployed nushell config
  programs.starship.enableNushellIntegration = false;
  programs.zoxide.enableNushellIntegration = false;
  programs.carapace.enableNushellIntegration = false;

  # Deploy nushell launcher script (sets PATH before exec-ing nu)
  # Referenced by: nix-darwin user shell, ghostty config, aerospace btop shortcut
  home.file.".local/bin/nushell" = {
    text = ''
      #!/bin/sh -l
      export XDG_CONFIG_HOME="$HOME/.config"
      export PATH="$HOME/.local/state/nix/profiles/home-manager/home-path/bin:$HOME/.nix-profile/bin:/opt/homebrew/bin:$PATH"
      exec nu --experimental-options='native-clip' "$@"
    '';
    executable = true;
  };

  # Deploy entire nushell tree EXCEPT the generated colors file
  xdg.configFile."nushell" = {
    source = nushellSource;
    recursive = true;
  };

  # Generated colors file — sourced by theme.nu
  xdg.configFile."nushell/confs/colors.nu".text = ''
    # Generated by Nix from nix/colors.nix
    # Do not edit — changes will be overwritten
    # See docs/colorscheme.md for reference

    let theme = {
      rosewater: "${h a.coral}"
      flamingo: "${h a.salmon}"
      pink: "${h a.pink}"
      mauve: "${h a.purple}"
      red: "${h a.red}"
      maroon: "${h a.red-soft}"
      peach: "${h a.orange}"
      yellow: "${h a.yellow}"
      green: "${h a.green}"
      teal: "${h a.teal}"
      sky: "${h a.cyan}"
      sapphire: "${h a.azure}"
      blue: "${h a.blue}"
      lavender: "${h a.lilac}"
      text: "${h s.fg}"
      subtext1: "${h s.fg-secondary}"
      subtext0: "${h s.fg-muted}"
      overlay2: "${h s.fg-faint}"
      overlay1: "${h s.border}"
      overlay0: "${h s.border-muted}"
      surface2: "${h s.surface-raised}"
      surface1: "${h s.surface}"
      surface0: "${h s.surface-sunken}"
      base: "${h bg.base}"
      mantle: "${h bg.mantle}"
      crust: "${h bg.crust}"
    }
  '';
}
