# Home Manager module: Nushell
# Deploys entire nushell config from source, generates colors.nu from nix/colors.nix
# Source-filter excludes the generated colors.nu path to avoid conflicts
# Also handles starship/zoxide/carapace integrations via HM modules

{ config, lib, pkgs, colors, ... }:

let
  h = colors.withHash;
  a = colors.accent.normal;
  s = colors.structural;
  bg = colors.background.override;

  # Filter out the generated colors.nu from the source tree
  nushellSource = lib.cleanSourceWith {
    src = ../../nushell.pkd/.config/nushell;
    filter = path: _type:
      !(lib.hasSuffix "/confs/colors.nu" path);
  };
in {
  programs.nushell = {
    enable = true;
  };

  # Starship integration (replaces manual `starship init nu` in env.nu)
  programs.starship.enableNushellIntegration = true;

  # Zoxide integration (replaces manual `zoxide init nushell` in env.nu)
  programs.zoxide = {
    enable = true;
    enableNushellIntegration = true;
  };

  # Carapace integration (replaces manual `carapace _carapace nushell` in env.nu)
  programs.carapace = {
    enable = true;
    enableNushellIntegration = true;
  };

  # Deploy entire nushell tree EXCEPT the generated colors file
  xdg.configFile."nushell" = {
    source = nushellSource;
    recursive = true;
  };

  # Generated colors file — sourced by theme.nu
  xdg.configFile."nushell/confs/colors.nu".text = ''
    # Generated by Nix from nix/colors.nix
    # Do not edit — changes will be overwritten
    # See docs/colorscheme.md for reference

    let theme = {
      rosewater: "${h a.coral}"
      flamingo: "${h a.salmon}"
      pink: "${h a.pink}"
      mauve: "${h a.purple}"
      red: "${h a.red}"
      maroon: "${h a.red-soft}"
      peach: "${h a.orange}"
      yellow: "${h a.yellow}"
      green: "${h a.green}"
      teal: "${h a.teal}"
      sky: "${h a.cyan}"
      sapphire: "${h a.azure}"
      blue: "${h a.blue}"
      lavender: "${h a.lilac}"
      text: "${h s.fg}"
      subtext1: "${h s.fg-secondary}"
      subtext0: "${h s.fg-muted}"
      overlay2: "${h s.fg-faint}"
      overlay1: "${h s.border}"
      overlay0: "${h s.border-muted}"
      surface2: "${h s.surface-raised}"
      surface1: "${h s.surface}"
      surface0: "${h s.surface-sunken}"
      base: "${h bg.base}"
      mantle: "${h bg.mantle}"
      crust: "${h bg.crust}"
    }
  '';
}
