# =====================================================================================
#                                                             _                     _
#     __ _   ___  _ __  ___   ___  _ __    __ _   ___  ___   | |_  ___   _ __ ___  | |
#    / _` | / _ \| '__|/ _ \ / __|| '_ \  / _` | / __|/ _ \  | __|/ _ \ | '_ ` _ \ | |
#  _| (_| ||  __/| |  | (_) |\__ \| |_) || (_| || (__|  __/ _| |_| (_) || | | | | || |
# (_)\__,_| \___||_|   \___/ |___/| .__/  \__,_| \___|\___|(_)\__|\___/ |_| |_| |_||_|
#                                 |_|
#
#                   Aerospace Configuration File
# =====================================================================================


# ========================= DOCUMENTATION =========================
# GUIDE: https://nikitabobko.github.io/AeroSpace/guide
# COMMANDS: https://nikitabobko.github.io/AeroSpace/commands#
# GOODIES: https://nikitabobko.github.io/AeroSpace/goodies
# GITHUB: https://github.com/nikitabobko/AeroSpace


# ========================= GLOBAL SETTINGS =========================

# launch borders-app: highlights border of focused windows
after-startup-command = ['exec-and-forget borders', 'exec-and-forget sketchybar']

# ========== auto-start ==========
start-at-login = true

# ========== Normalizations ==========
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# ========== accordian ==========
accordion-padding = 30

# ========== layout defaults ==========
# tiles|accordion
default-root-container-layout = 'tiles'

# horizontal|vertical|auto
default-root-container-orientation = 'auto'

# ========== disable macos hide behavior ==========
automatically-unhide-macos-hidden-apps = true

# ========== events ==========
exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

on-focused-monitor-changed = 'move-mouse monitor-lazy-center'

# ========== monitor settings ==========
[workspace-to-monitor-force-assignment]
1 = 'built-in'
2 = 'main'
3 = 'main'

4 = 'secondary' 
5 = 'secondary' 
6 = 'secondary'

# ========== keyboard layout ==========
[key-mapping]
preset = 'qwerty'

# ========== window spacing ==========
[gaps]

# between windows
inner.horizontal = 8
inner.vertical = 8

# between windows and screen edge
outer.left = 8
outer.bottom = 8
outer.right = 8
outer.top = [
  { monitor."built-in" = 10 },
  { monitor."main" = 40 },
  40
]

# ========================= APP SPECIFIC SETTINGS =========================

# macOS native
[[on-window-detected]]
if.app-name-regex-substring = 'messages|finder|find my|maps|reminders|calendar|music|weather|activity monitor|photos|mail|passwords|clock'
run = 'layout floating'

# non-native
[[on-window-detected]]
if.app-name-regex-substring = 'crossover|steam'
run = 'layout floating'

# ========================= MAIN BINDINGS =========================
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# ========================= GENERAL HOTKEYS =========================

# ========================= APPLICATION HOTKEYS =========================

# GHOSTTY
cmd-alt-ctrl-space = 'exec-and-forget open -na ghostty'

# CALCULATOR
cmd-alt-ctrl-c = 'exec-and-forget open -a calculator'
# cmd-alt-ctrl-shift-c = 'exec-and-forget open -na calculator'

# MESSAGES
cmd-alt-ctrl-m = 'exec-and-forget open -a messages'

# ZEN
cmd-alt-ctrl-z = 'exec-and-forget open -n /Applications/Zen.app'

# MAIL
cmd-alt-ctrl-g = '''exec-and-forget osascript -e 'tell application "Mail"
    check for new mail
end tell'; open -a Mail'''

# IPHONE MIRRORING
cmd-alt-ctrl-p = 'exec-and-forget open -a "iphone mirroring"'

# UTM vm software
cmd-alt-ctrl-v = 'exec-and-forget open -a "UTM"'

# discord
cmd-alt-ctrl-d = 'exec-and-forget open -a "discord"'

# ========================= TILING HOTKEYS =========================

# ========== layout ==========
cmd-alt-ctrl-shift-enter = 'layout h_tiles h_accordion'
cmd-alt-ctrl-enter = 'layout floating tiling'
cmd-alt-ctrl-r = 'flatten-workspace-tree'
cmd-alt-ctrl-shift-r = [ 'reload-config', 'exec-and-forget sketchybar --reload' ]

# ========== focus ==========
cmd-alt-ctrl-h = 'focus left'
cmd-alt-ctrl-j = 'focus down'
cmd-alt-ctrl-k = 'focus up'
cmd-alt-ctrl-l = 'focus right'

# ========== move windows ==========
cmd-alt-ctrl-shift-h = 'move left'
cmd-alt-ctrl-shift-j = 'move down'
cmd-alt-ctrl-shift-k = 'move up'
cmd-alt-ctrl-shift-l = 'move right'

cmd-alt-ctrl-left = 'join-with left'
cmd-alt-ctrl-down = 'join-with down'
cmd-alt-ctrl-up = 'join-with up'
cmd-alt-ctrl-right = 'join-with right'

# ========== resize windows ==========
cmd-alt-ctrl-minus = 'resize smart -50'
cmd-alt-ctrl-equal = 'resize smart +50'

# ========== workspaces ==========
cmd-alt-ctrl-1 = 'workspace 1'
cmd-alt-ctrl-2 = 'workspace 2'
cmd-alt-ctrl-3 = 'workspace 3'
cmd-alt-ctrl-4 = 'workspace 4'
cmd-alt-ctrl-5 = 'workspace 5'
cmd-alt-ctrl-6 = 'workspace 6'
# cmd-alt-ctrl-7 = 'workspace 7'
# cmd-alt-ctrl-8 = 'workspace 8'
# cmd-alt-ctrl-9 = 'workspace 9'

cmd-alt-ctrl-shift-1 = 'move-node-to-workspace 1'
cmd-alt-ctrl-shift-2 = 'move-node-to-workspace 2'
cmd-alt-ctrl-shift-3 = 'move-node-to-workspace 3'
cmd-alt-ctrl-shift-4 = 'move-node-to-workspace 4'
cmd-alt-ctrl-shift-5 = 'move-node-to-workspace 5'
cmd-alt-ctrl-shift-6 = 'move-node-to-workspace 6'
# cmd-alt-ctrl-shift-7 = 'move-node-to-workspace 7'
# cmd-alt-ctrl-shift-8 = 'move-node-to-workspace 8'
# cmd-alt-ctrl-shift-9 = 'move-node-to-workspace 9'

# ========== monitors ==========
cmd-alt-ctrl-tab = 'focus-monitor --wrap-around next'
cmd-alt-ctrl-shift-tab = [
  'move-node-to-monitor --wrap-around next',
  'focus-monitor --wrap-around next',
]
