repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
      - id: check-toml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
        name: Detect Private Keys

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.92.2
    hooks:
      - id: trufflehog
        name: TruffleHog Secret Scanner
        entry:
          trufflehog git file://. --since-commit HEAD --results=verified,unknown
          --fail
        args: []

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.0.2
    hooks:
      - id: stylua

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-2
    hooks:
      - id: shfmt
        args: ["-w", "-s", "-i", "2"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]
        exclude: ^.*\.pkd/

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

exclude: ^.*\.(spl|lock)|\.git/|lazy-lock\.json|.*\.nu$|.*art/
