#!/bin/bash

# ========================================================================
#            _                                       _       _
#         __| |_   _ _ __ ___  _ __    ___  ___ _ __(_)_ __ | |_
#        / _` | | | | '_ ` _ \| '_ \  / __|/ __| '__| | '_ \| __|
#       | (_| | |_| | | | | | | |_) | \__ \ (__| |  | | |_) | |_
#        \__,_|\__,_|_| |_| |_| .__/  |___/\___|_|  |_| .__/ \__|
#                             |_|                     |_|
#         Script to dump cronjobs & brew packages for git tracking
# ========================================================================

# filepaths
STORAGE_DIR="${HOME}/dotfiles/_dumps"
BREW_PATH="${STORAGE_DIR}/Brewfile"
CRON_PATH="${STORAGE_DIR}/Cronjobs"

# dump brewfile
rm -f "$BREW_PATH"

if (brew bundle dump --no-vscode --file="$BREW_PATH"); then
  echo "Dumping brew bundle"
else
  echo "FAILED: could not dump brew bundle"
  exit 1
fi

# dump cron jobs

if (crontab -l >"$CRON_PATH"); then
  echo "Dumping crontab"
else
  echo "FAILED: could not dump crontab"
  exit 1
fi
