#!/bin/bash

# ============================================================
#                                  _                         #
#           __ _ _ __  _   _   ___| |_ _____      __         #
#          / _` | '_ \| | | | / __| __/ _ \ \ /\ / /         #
#         | (_| | | | | |_| | \__ \ || (_) \ V  V /          #
#          \__, |_| |_|\__,_| |___/\__\___/ \_/\_/           #
#          |___/                                             #
#              stow wrapper to setup dotfiles                #
# ============================================================

if [[ "$1" == "-m" ]] || [[ "$1" == "-h" ]]; then
	FLAG="$1"
	ACTION="$2"
else
	FLAG="NIL"
	ACTION="$1"
fi


if [[ "$FLAG" == "-h" ]] || (( $# == 0 )); then
  echo -e "Needs command:\n"
  echo -e "\ttest: dry run"
  echo -e "\tlink: apply links"
  echo -e "\tunlink: delete all links"
  exit 0
fi

case "$FLAG" in
	"-m")
		# minimal setup
		case "$ACTION" in
			"test")
				#stow -nv *.pkg
				echo "minimal test"
				;;
			"link")
				#stow -v *.pkg
				echo "minimal link"
				;;
			"unlink")
				#stow -Dv *.pkg
				echo "minimal unlink"
				;;
			*)
				echo "Unknown command: '$ACTION'"
				exit 1
				;;
		esac
		;;
	"NIL")
		# full setup
		case "$ACTION" in
			"test")
				TEMP="*.pkg"
				echo $TEMP
				stow -nv *.pkg
				;;
			"link")
				#stow -v *.pkg
				echo "full link"
				;;
			"unlink")
				#stow -Dv *.pkg
				echo "full unlink"
				;;
			*)
				echo "Unknown command: '$ACTION'"
				exit 1
				;;
		esac
		;;
	*)
		echo "Unkown flag: '$FLAG'"
		exit 1
		;;
esac
