#!/bin/bash

# ========================================================== #
#                                  _                         #
#           __ _ _ __  _   _   ___| |_ _____      __         #
#          / _` | '_ \| | | | / __| __/ _ \ \ /\ / /         #
#         | (_| | | | | |_| | \__ \ || (_) \ V  V /          #
#          \__, |_| |_|\__,_| |___/\__\___/ \_/\_/           #
#          |___/                                             #
#              stow wrapper to setup dotfiles                #
# ========================================================== #

# default args
ARGUMENTS=(
  "--target"
  "$HOME"
  "--dir"
  "$HOME/dotfiles"
  "--dotfiles"
  "-v"
)

# file extension for packages
FILE_EXTENSION="pkd"

# help message
if [[ "$1" == "-h" || "$1" == "--help" ]] || (( $# == 0 )); then
  echo -e "Usage"
  echo -e "\t$(basename $0) [options] <package> [<package> ...]"
  echo -e "\nOptions"
  echo -e "\t-h, --help\t\t this helpful message"
  echo -e "\t-a, --all\t\t stow all packages"
  echo -e "\t-t, --test\t\t testing mode, no change to file system"
  echo -e "\t-e, --exclude\t exclude packages passed"
  echo -e "\t-d, --delete\t\t delete existing links"
  echo -e "\nArguments"
  echo -e "\t<package>\t\t package basename to stow"
  exit 0
fi

# init variables
ALL_FLAG=false
EXCLUDE_FLAG=false
TARGETS=()

# parse arguments
for ARG in "$@"; do
  case "$ARG" in
    -a|--all)
      ALL_FLAG=true
      ;;
    -t|--test)
      ARGUMENTS+=("--no")
      ;;
    -e|--exclude)
      EXCLUDE_FLAG=true
      ;;
    -d|--delete)
      ARGUMENTS+=("--delete")
      ;;
    *)
      if ! [ -d "$ARG.$FILE_EXTENSION" ]; then
        echo -e "Package Not Found: $ARG.$FILE_EXTENSION"
        exit 1
      fi
      TARGETS+=("$ARG.$FILE_EXTENSION")
  esac
done

# read stowignore file
while IFS= read -r LINE; do
  ARGUMENTS+=("--ignore=$LINE")
done < .stowignore

if $ALL_FLAG; then
  ARGUMENTS+=(*.$FILE_EXTENSION)
elif $EXCLUDE_FLAG; then
  for pkg in *.$FILE_EXTENSION; do
      skip=false
      for target in "${TARGETS[@]}"; do
        if [[ "$pkg" == "$target" ]]; then
          skip=true
          break
        fi
      done
      if ! $skip; then
        ARGUMENTS+=("$pkg")
      fi
    done
else
  for TARGET in "${TARGETS[@]}" ; do
    ARGUMENTS+=("$TARGET")
  done
fi

stow "${ARGUMENTS[@]}"
