--- Language Tool Name Mappings
---
--- Contains mappings for:
--- 1. LSP server names to Mason package names (lsp_to_mason)
--- 2. Tool names to null-ls source providers (tool_to_nullls)
---
--- Source: mason-lspconfig package specs, null-ls builtins, none-ls-extras
--- Maintained manually - update when adding new tools.
--- See lua/lang-system/README.md for usage documentation.

local M = {}

--- Map from lspconfig server name to Mason package name.
--- @type table<string, string>
M.lsp_to_mason = {
  ada_language_server = "ada-language-server",
  air = "air",
  aiken = "aiken",
  angularls = "angular-language-server",
  ansiblels = "ansible-language-server",
  antlersls = "antlers-language-server",
  apex_ls = "apex-language-server",
  arduino_language_server = "arduino-language-server",
  asm_lsp = "asm-lsp",
  ast_grep = "ast-grep",
  astro = "astro-language-server",
  autohotkey_lsp = "autohotkey",
  autotools_ls = "autotools-language-server",
  awk_ls = "awk-language-server",
  azure_pipelines_ls = "azure-pipelines-language-server",
  bacon_ls = "bacon-ls",
  basedpyright = "basedpyright",
  bashls = "bash-language-server",
  beancount = "beancount-language-server",
  bicep = "bicep-lsp",
  biome = "biome",
  bqls = "bqls",
  bright_script = "brighterscript",
  bsl_ls = "bsl-language-server",
  buf_ls = "buf",
  bzl = "bzl",
  c3lsp = "c3-lsp",
  cairo_ls = "cairo-language-server",
  cds_lsp = "cds-lsp",
  circom_lsp = "circom-lsp",
  clangd = "clangd",
  clarinet = "clarinet",
  clojure_lsp = "clojure-lsp",
  cmake = "cmake-language-server",
  cobol_ls = "cobol-language-support",
  codebook = "codebook",
  coq_lsp = "coq-lsp",
  crystalline = "crystalline",
  csharp_ls = "csharp-language-server",
  css_variables = "css-variables-language-server",
  csskit = "csskit",
  cssls = "css-lsp",
  cssmodules_ls = "cssmodules-language-server",
  cucumber_language_server = "cucumber-language-server",
  cue = "cue",
  cypher_ls = "cypher-language-server",
  dagger = "cuelsp",
  dhl_lsp = "dhall-lsp",
  diagnosticls = "diagnostic-languageserver",
  digestif = "digestif",
  dingo_lsp = "dingo-lsp",
  djls = "django-language-server",
  djlsp = "django-template-lsp",
  docker_compose_language_service = "docker-compose-language-service",
  docker_language_server = "docker-language-server",
  dockerls = "dockerfile-language-server",
  dotls = "dot-language-server",
  dprint = "dprint",
  drools_lsp = "drools-lsp",
  earthls = "earthlyls",
  elixirls = "elixir-ls",
  elmls = "elm-language-server",
  elp = "erlang-ls",
  ember = "ember-language-server",
  emmet_language_server = "emmet-language-server",
  emmet_ls = "emmet-ls",
  emmylua_ls = "emmylua",
  erg_language_server = "erg-language-server",
  esbonio = "esbonio",
  eslint = "eslint-lsp",
  expert = "expert",
  facility_language_server = "facility-language-server",
  fennel_language_server = "fennel-language-server",
  fennel_ls = "fennel-ls",
  fish_lsp = "fish-lsp",
  foam_ls = "foam-language-server",
  fortitude = "fortitude",
  fortls = "fortls",
  fsautocomplete = "fsautocomplete",
  gh_actions_ls = "gh-actions-language-server",
  ginko_ls = "ginko",
  gitlab_ci_ls = "gitlab-ci-ls",
  glint = "glint",
  glsl_analyzer = "glsl",
  glslls = "glslls",
  gn_language_server = "gn-language-server",
  golangci_lint_ls = "golangci-lint-langserver",
  gopls = "gopls",
  gradle_ls = "gradle-language-server",
  grammarly = "grammarly-languageserver",
  graphql = "graphql-language-service-cli",
  groovyls = "groovy-language-server",
  harper_ls = "harper-ls",
  hdl_checker = "hdl-checker",
  haxe_language_server = "haxe-language-server",
  helm_ls = "helm-ls",
  herb_ls = "herb-language-server",
  hoon_ls = "hoon-language-server",
  html = "html-lsp",
  htmx = "htmx-lsp",
  hydra_lsp = "hydra-lsp",
  hylo_ls = "hylo-language-server",
  hyprls = "hyprls",
  intelephense = "intelephense",
  java_language_server = "java-language-server",
  jdtls = "jdtls",
  jedi_language_server = "jedi-language-server",
  jinja_lsp = "jinja-lsp",
  jqls = "jq-lsp",
  jsonls = "json-lsp",
  jsonnet_ls = "jsonnet-language-server",
  julials = "julia-lsp",
  just = "just-lsp",
  kcl = "kcl",
  kotlin_language_server = "kotlin-language-server",
  kotlin_lsp = "kotlin-lsp",
  laravel_ls = "laravel-ls",
  leanls = "lean-language-server",
  lelwel_ls = "lelwel",
  lemminx = "lemminx",
  lexical = "lexical",
  llm_ls = "llm-ls",
  ltex = "ltex-ls",
  ltex_plus = "ltex-ls-plus",
  lua_ls = "lua-language-server",
  luau_lsp = "luau-lsp",
  lwc_ls = "lwc-language-server",
  m68k = "m68k-lsp-server",
  markdown_oxide = "markdown-oxide",
  marksman = "marksman",
  matlab_ls = "matlab-language-server",
  mdx_analyzer = "mdx-analyzer",
  mesonlsp = "mesonlsp",
  mm0_ls = "metamath-zero-lsp",
  millet = "millet",
  motoko_lsp = "motoko-lsp",
  move_analyzer = "move-analyzer",
  mpls = "mpls",
  mutt_ls = "mutt-language-server",
  neocmake = "neocmakelsp",
  nextflow_ls = "nextflow-language-server",
  nextls = "nextls",
  nginx_language_server = "nginx-language-server",
  nickel_ls = "nickel-lang-lsp",
  nil_ls = "nil",
  nim_langserver = "nimlangserver",
  nimls = "nimlsp",
  ocamllsp = "ocaml-lsp",
  ols = "ols",
  omnisharp = "omnisharp",
  opencl_ls = "opencl-language-server",
  openscad_lsp = "openscad-lsp",
  oxfmt = "oxfmt",
  oxlint = "oxlint",
  pbls = "pbls",
  perlnavigator = "perlnavigator",
  pest_ls = "pest-language-server",
  phpactor = "phpactor",
  postgres_lsp = "postgres-language-server",
  powershell_es = "powershell-editor-services",
  prismals = "prisma-language-server",
  prosemd_lsp = "prosemd-lsp",
  protols = "protols",
  psalm = "psalm",
  purescriptls = "purescript-language-server",
  pylsp = "python-lsp-server",
  pylyzer = "pylyzer",
  pyre = "pyre",
  pyrefly = "pyrefly",
  pyright = "pyright",
  qmlls = "qmlls",
  quick_lint_js = "quick-lint-js",
  r_language_server = "r-languageserver",
  raku_navigator = "raku-navigator",
  reason_ls = "reason-language-server",
  regal = "regal",
  regols = "regols",
  remark_ls = "remark-language-server",
  rescriptls = "rescript-language-server",
  robotcode = "robotcode",
  robotframework_ls = "robotframework-lsp",
  roc_ls = "roc",
  rpmspec = "rpm",
  rubocop = "rubocop",
  ruby_lsp = "ruby-lsp",
  ruff = "ruff",
  rumdl = "rumdl",
  rust_analyzer = "rust-analyzer",
  serve_d = "serve-d",
  shopify_theme_ls = "shopify-cli",
  sith_language_server = "sith-language-server",
  slint_lsp = "slint-lsp",
  smithy_ls = "smithy-language-server",
  snyk_ls = "snyk-ls",
  solang = "solang",
  solargraph = "solargraph",
  solc = "solc",
  solidity = "solidity",
  solidity_ls = "solidity-ls",
  solidity_ls_nomicfoundation = "nomicfoundation-solidity-language-server",
  somesass_ls = "some-sass-language-server",
  sorbet = "sorbet",
  spectral = "spectral-language-server",
  spyglassmc_language_server = "spyglassmc-language-server",
  sqlls = "sqlls",
  sqls = "sqls",
  sqruff = "sqruff",
  stan_ls = "stan-language-server",
  standardrb = "standardrb",
  starlark_rust = "starlark-rust",
  starpls = "starpls",
  steep = "steep",
  stimulus_ls = "stimulus-language-server",
  stylelint_lsp = "stylelint-language-server",
  superhtml = "superhtml",
  svelte = "svelte-language-server",
  svlangserver = "svlangserver",
  svls = "svls",
  tailwindcss = "tailwindcss-language-server",
  taplo = "taplo",
  tclsp = "tclint",
  teal_ls = "teal-language-server",
  templ = "templ",
  terraformls = "terraform-ls",
  texlab = "texlab",
  textlsp = "textlsp",
  tflint = "tflint",
  thriftls = "thriftls",
  tinymist = "tinymist",
  tofuls = "tofu-ls",
  tombi = "tombi",
  ts_ls = "typescript-language-server",
  tsgo = "tsgo",
  tsp_server = "tsp-server",
  ty = "ty",
  twiggy_language_server = "twiggy-language-server",
  unocss = "unocss-language-server",
  v_analyzer = "v-analyzer",
  vacuum = "vacuum",
  vala_ls = "vala-language-server",
  vale_ls = "vale-ls",
  verible = "verible",
  veryl_ls = "veryl-ls",
  vhdl_ls = "vhdl-style-guide",
  vimls = "vim-language-server",
  visualforce_ls = "visualforce-language-server",
  vls = "vls",
  vtsls = "vtsls",
  vue_ls = "vue-language-server",
  wasm_language_tools = "wasm-language-tools",
  wc_ls = "wc-language-server",
  wgsl_analyzer = "wgsl-analyzer",
  yamlls = "yaml-language-server",
  yls_yara = "yls-yara",
  zk = "zk",
  zls = "zls",
  zuban = "zuban",
}

--- Map from config tool name to null-ls source name.
--- null-ls uses different names than Mason packages or tool executables.
--- Used to look up sources in null_ls.builtins or none-ls-extras.
--- @type table<string, table<string, { source: string, provider: "builtin"|"extras" }>>
M.tool_to_nullls = {
  diagnostics = {
    eslint_d = { source = "eslint_d", provider = "extras" },
    ruff = { source = "ruff", provider = "extras" },
    selene = { source = "selene", provider = "builtin" },
    yamllint = { source = "yamllint", provider = "builtin" },
  },
  formatting = {
    black = { source = "black", provider = "builtin" },
    ["clang-format"] = { source = "clang_format", provider = "builtin" },
    eslint = { source = "eslint", provider = "extras" },
    gofumpt = { source = "gofumpt", provider = "builtin" },
    ["google-java-format"] = { source = "google_java_format", provider = "builtin" },
    prettier = { source = "prettier", provider = "builtin" },
    ruff = { source = "ruff", provider = "extras" },
    rustfmt = { source = "rustfmt", provider = "extras" },
    shfmt = { source = "shfmt", provider = "builtin" },
    stylua = { source = "stylua", provider = "builtin" },
    ["tex-fmt"] = { source = "tex_fmt", provider = "extras" },
    nufmt = { source = "nufmt", provider = "local" },
  },
}

return M
