#! /bin/bash

# ==========================================================================================
#
#                      _        _       _           _
#                  ___| | _____| |_ ___| |__  _   _| |__   __ _ _ __ _ __ ___
#                 / __| |/ / _ \ __/ __| '_ \| | | | '_ \ / _` | '__| '__/ __|
#                 \__ \   <  __/ || (__| | | | |_| | |_) | (_| | |  | | | (__
#                 |___/_|\_\___|\__\___|_| |_|\__, |_.__/ \__,_|_|  |_|  \___|
#                                             |___/
#
#                                 SketchyBar Configuration File
#
# ==========================================================================================


# ==================== TODO ====================

# TODO:
# - clicking on a workspace reveals the windows in it (dropdown)
#   - aerospace list-windows --workspace 2 --format "%{app-name} -> %{window-title}"
#   - trim with trimmed_string="${my_string:0:$desired_length}"
# - get unread imessages?

# ==================== Setup ====================

source "$CONFIG_DIR/aesthetics.sh"
export SCRIPT_DIR="$CONFIG_DIR/scripts"
COMPONENT_DIR="$CONFIG_DIR/components"

# ==================== Settings ==================== 
# NOTE: order is out to in

left_items=(
  "aerospace"
  "focus_app"
)

right_items=(
  "clock"
  "wifi"
  "battery"
  "volume"
  "mail"
)

bar=(
  height="$BAR_HEIGHT"
  color="$BAR_COLOR"
  shadow-"$SHADOW"
  position="$BAR_POSITION"
  sticky="$BAR_STICKY"
  blur_radius="$BAR_BLUR_RADIUS"
  corner_radius="$BAR_CORNER_RADIUS"
)

default=(
  updates=when_shown
  padding_left="$PADDING"
  padding_right="$PADDING"
  icon.font="$FONT:Bold:$ICON_SIZE"
  label.font="$FONT:Bold:$FONT_SIZE"
  icon.color="$ICON_COLOR"
  label.color="$LABEL_COLOR"
  icon.padding_left="$ICON_PADDING"
  icon.padding_right="$ICON_PADDING"
  label.padding_left="$ICON_PADDING"
  label.padding_right="$ICON_PADDING"
)

# ==================== Setup ====================

sketchybar --bar "${bar[@]}" --default "${default[@]}" 

for item in "${left_items[@]}"; do
  source "$COMPONENT_DIR/$item.sh" left
done

for item in "${right_items[@]}"; do
  source "$COMPONENT_DIR/$item.sh" right
done

source "$COMPONENT_DIR/left_bracket.sh"
source "$COMPONENT_DIR/right_bracket.sh"

# ==================== Run Scripts ====================
# WARNING: never do this in a script

sketchybar --update

# ensure a workspace is highlighted
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE="$(aerospace list-workspaces --focused)"
