#!/bin/bash

# A program for interactively choosing aerc command options, intended to be run with :menu

MENU="$1"
if [ -z "$MENU" ] || [ $# -gt 1 ]; then
  exit 1
fi

if ! (which pick >/dev/null); then
  exit 2
fi

function getvalue() {
  local target="$1"
  for pair in "${PAIRS[@]}"; do
    key="${pair%%:*}"
    if [ "$key" == "$target" ]; then
      echo "${pair#*:}"
      return 0
    fi
  done
  exit 1
}

function getkeys() {
  for pair in "${PAIRS[@]}"; do
    echo "${pair%%:*}"
  done
}

declare -a PAIRS

case "$MENU" in
  "reply")
      PAIRS+=("[1] Reply:-T new_message")
      PAIRS+=("[2] Reply-All:-a")
      PAIRS+=("[3] Reply Quoted:-q")
      PAIRS+=("[4] Reply-All Quoted:-qa")
    ;;
  "flag")
    PAIRS+=("Flagged:-t -x flagged")
    PAIRS+=("Draft:-t -x draft")
    PAIRS+=("Answered:-t -x answered")
    PAIRS+=("Forwarded:-t -x forwarded")
    PAIRS+=("Seen:-t -x seen")
    ;;
  "info")
    PAIRS+=("Tags:Flags: {{.Flags}} Labels: {{.Labels}}")
    PAIRS+=("Files:Files: {{.Filenames}}")
    PAIRS+=("Size:Size: {{.Size | humanReadable}}")
    PAIRS+=("Names:Peers: {{.Peer | names}}")
    PAIRS+=("Emails:Peers: {{.Peer | emails}}")
    PAIRS+=("Date:Date: {{.Date.Local}} Original: {{.OriginalDate.Local}}")
    ;;
  "sort"|"rsort")
    F=$(if [ "$MENU" == "rsort" ]; then echo "-r "; else echo ""; fi)
    PAIRS+=("Time - Arrival:${F}arrival")
    PAIRS+=("Time - Creation:${F}date")
    PAIRS+=("Sender:${F}from")
    PAIRS+=("Receiver:${F}to")
    PAIRS+=("CCed:${F}cc")
    PAIRS+=("Priority:${F}flagged")
    PAIRS+=("Subject Line:${F}subject")
    PAIRS+=("Size:${F}size")
    PAIRS+=("Read:${F}read")
    ;;
  "help")
    PAIRS+=("Commands:aerc")
    PAIRS+=("Keybindings:keys")
    PAIRS+=("Search:search")
    PAIRS+=("Tutorial:tutorial")
    PAIRS+=("Patchfiles:patch")
    PAIRS+=("String Interpolation (templates):templates")
    PAIRS+=(" : ")
    PAIRS+=("Conf - aerc.conf:config")
    PAIRS+=("Conf - accounts.conf:accounts")
    PAIRS+=("Conf - binds.conf:binds")
    PAIRS+=("Conf - stylesets/*:stylesets")
    PAIRS+=("Conf - Notmuch:notmuch")
    PAIRS+=("Conf - Sendmail:sendmail")
    PAIRS+=("Conf - SMTP:smtp")
    PAIRS+=("Conf - IMAP:imap")
    PAIRS+=("Conf - JMAP:jmap")
    ;;
  *)
    exit 1
    ;;
esac

PAIRS+=("[Cancel]:")

CHOICE=$(getkeys | pick -S)

if [ "$CHOICE" == "Cancel" ]; then
  exit 0
fi

getvalue "$CHOICE"
