#! /bin/bash

FORCE=0
KEEP=0
REVERSE=0
IS_DIR=0

while getopts "fkhr" opt; do
  case "$opt" in
  r)
    REVERSE=1
    ;;
  f)
    FORCE=1
    ;;
  k)
    KEEP=1
    ;;
  h)
    echo -e "Usage: backup file\n"
    echo -e "Options:"
    echo -e "\t-h\t\tthis help message"
    echo -e "\t-f\t\toverwrite pre-existing backups"
    echo -e "\t-k\t\tkeep original file"
    echo -e "\t-r\t\treverse (remove .bak)"
    exit 0
    ;;
  \?)
    echo "ERR: invalid option"
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

if (($# != 1)); then
  echo "ERR: invalid number of args"
  exit 1
fi

FILE="$1"
if ! [ -f "$FILE" ]; then
  echo "ERR: $FILE not found"
  exit 1
fi

if ((REVERSE)); then

  if ! [[ "$FILE" == *.bak ]]; then
    echo "ERR: file cannot be reversed, not *.bak"
    exit 1
  fi

  UNBACKUP="${FILE%.bak}"
  
  if [ -f "$UNBACKUP" ]; then
    if ((FORCE)); then
      \rm -rf "$UNBACKUP"
    else
      echo "ERR: Original already present. Use -f to overwrite"
      exit 1
    fi
  fi

  if ((KEEP)); then
    cp -R "$FILE" "$UNBACKUP"
  else
    mv "$FILE" "$UNBACKUP"
  fi

else
  BACKUP="$1.bak"

  if [ -f "$BACKUP" ] || [ -d "$BACKUP" ]; then
    if ((FORCE)); then
      \rm -rf "$BACKUP"
    else
      echo "ERR: Backup already present. Use -f to overwrite"
      exit 1
    fi
  fi

  if ((KEEP)); then
    cp -R "$FILE" "$BACKUP"
  else
    mv "$FILE" "$BACKUP"
  fi
fi
