#! /bin/bash

FORCE=0
KEEP=0
IS_DIR=0

while getopts "fkh" opt; do
  case "$opt" in
  f)
    FORCE=1
    ;;
  k)
    KEEP=1
    ;;
  h)
    echo -e "Usage: backup file\n"
    echo -e "Options:"
    echo -e "\t-h\t\tthis help message"
    echo -e "\t-f\t\toverwrite pre-existing backups"
    echo -e "\t-k\t\tkeep original file"
    exit 0
    ;;
  \?)
    echo "ERR: invalid option"
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

if (($# != 1)); then
  echo "ERR: invalid number of args"
  exit 1
fi

FILE="$1"
BACKUP="$1.bak"

if [ -d "$FILE" ]; then
  IS_DIR=1
elif ! [ -f "$FILE" ]; then
  echo "ERR: $FILE not found"
  exit 1
fi

if [ -f "$BACKUP" ] || [ -d "$BACKUP" ]; then
  if (($FORCE)); then
    \rm -rf "$BACKUP"
  else
    echo "ERR: Backup already present. Use -f to overwrite"
    exit 1
  fi
fi

if (($KEEP)); then
  cp -R "$FILE" "$BACKUP"
else
  mv "$FILE" "$BACKUP"
fi
