#! /bin/bash

FORCE=0
KEEP=0
REVERSE=0

while getopts "fkhr" opt; do
  case "$opt" in
  r)
    REVERSE=1
    ;;
  f)
    FORCE=1
    ;;
  k)
    KEEP=1
    ;;
  h)
    echo -e "Usage: backup file\n"
    echo -e "Options:"
    echo -e "\t-h\t\tthis help message"
    echo -e "\t-f\t\toverwrite pre-existing backups"
    echo -e "\t-k\t\tkeep original file"
    echo -e "\t-r\t\treverse (remove .bak)"
    exit 0
    ;;
  \?)
    echo "ERR: '$opt' not a valid option"
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

for arg in "$@"; do

  FILE="$arg"
  if ! [ -f "$FILE" ] && ! [ -d "$FILE" ]; then
    echo "ERR: '$FILE' not found"
    continue
  fi

  if ((REVERSE)); then

    if ! [[ "$FILE" == *.bak ]]; then
      echo "ERR: '$FILE' cannot be reversed, not *.bak"
      continue
    fi

    UNBACKUP="${FILE%.bak}"
    
    if [ -f "$UNBACKUP" ] || [ -d "$UNBACKUP" ]; then
      if ((FORCE)); then
        \rm -rf "$UNBACKUP"
      else
        echo "ERR: '$UNBACKUP' already present. Use -f to overwrite"
        continue
      fi
    fi

    if ((KEEP)); then
      cp -R "$FILE" "$UNBACKUP"
    else
      mv "$FILE" "$UNBACKUP"
    fi

  else
    BACKUP="$FILE.bak"

    if [ -f "$BACKUP" ] || [ -d "$BACKUP" ]; then
      if ((FORCE)); then
        \rm -rf "$BACKUP"
      else
        echo "ERR: '$BACKUP' already present. Use -f to overwrite"
        continue
      fi
    fi

    if ((KEEP)); then
      cp -R "$FILE" "$BACKUP"
    else
      mv "$FILE" "$BACKUP"
    fi
  fi
done
