#!/bin/zsh

# ======================================= #
#                  _                      #
#          _______| |__  _ __ ___         #
#         |_  / __| '_ \| '__/ __|        #
#        _ / /\__ \ | | | | | (__         #
#       (_)___|___/_| |_|_|  \___|        #
#          ZSH Configuration File         #
# ======================================= #

# ==================== INTERACTIVITY CHECK ====================

if [[ $- != *i* ]]; then
  return
fi

# ==================== CORE SETTINGS & VARIABLES ====================

SHELL_CONFIG="$HOME/dotfiles/zsh.pkg"

function shell_source() {
  if ! [ -f "$SHELL_CONFIG/$1.zsh" ]; then
    echo "$1.zsh could not be sourced"
  fi
  source "$SHELL_CONFIG/$1.zsh"
}

shell_source settings

# ==================== OPERATING SYSTEM DETECTION ====================

case "$OSTYPE" in
  linux*)
    OPERATING_SYSTEM="linux"
    shell_source linux
    HOSTNAME=$(hostname | \grep -E -o '^[^.]+')
    ;;
  darwin*)
    OPERATING_SYSTEM="macos"
    shell_source macos
    HOSTNAME=$(scutil --get ComputerName)
    ;;
  *)
    OPERATING_SYSTEM=""
    HOSTNAME="HOSTNAME NOT FOUND"
    ERROR_STATUS="$ERROR_STATUS\n\tNot a supported OS. ($OSTYPE)"
    ;;
esac

# ==================== TIMEKEEPING ====================

START_TIME=$(gdate +%s%3N)

# ==================== SOURCING ====================

local ZSH_MODULES=(
  "zinit"
  "zsh"
  "path"
  "zoxide"
  "colorize"
  "fzf"
  "functions"
  "aliases"
)

for module in $ZSH_MODULES[@]; do
  shell_source $module
done

# shell_source zinit
#
# shell_source zsh
#
# shell_source path
#
# shell_source zoxide
#
# shell_source colorize
#
# shell_source fzf
#
# shell_source functions
#
# shell_source aliases

# ==================== IMPORT FROM PACKAGES ====================

local DOTFILES_DIR="$HOME/dotfiles"

for package in $DOTFILES_DIR/*.pkg; do
  if [ -f "$package/init.zsh" ]; then
    source "$package/init.zsh"
  fi
done

if [ -f "$DOTFILES_DIR/scripts/init.zsh" ]; then
  source "$DOTFILES_DIR/scripts/init.zsh"
fi

# ==================== ERROR CHECK ====================

if [[ "$ERROR_STATUS" != "" ]]; then
  DO_SPLASH_SCREEN=0
  local MESSAGE_LENGTH=35
  echo -ne "\n\n\033[91mErrors During Zsh Initialization\033[90m "
  for _ in {$MESSAGE_LENGTH..$COLUMNS}; do
    echo -n "="
  done
  echo -e "\033[0m"
  echo -e "$ERROR_STATUS"
  echo -e " \033[90m"
  for _ in {2..$COLUMNS}; do
    echo -n "="
  done
  echo "\033[0m\n\n"
fi

# ==================== SPLASH SCREEN ==================== 

if (( DO_SPLASH_SCREEN )); then
  shell_source splash_screen
fi

# ==== DISPLAY LOAD TIME ====

echo "\033[90mzsh load time: $(( $(gdate +%s%3N) - START_TIME ))ms\033[0m"

# ==================== PROMPT & CURSOR ==================== 

shell_source prompt

# Created by `pipx` on 2025-11-12 07:17:28
export PATH="$PATH:/Users/scc/.local/bin"
