#!/usr/bin/env bash

USER_CONFIG="${CONFIG_DIR:-$HOME/.config/sketchybar}/user.sketchybarrc"
if [ -f "$USER_CONFIG" ]; then
  source "$USER_CONFIG"
fi

export SBAR_THEME="${SBAR_THEME:-onedark}"
THEME_FILE="${CONFIG_DIR:-$HOME/.config/sketchybar}/tokens/themes/$SBAR_THEME.sh"
if [ -f "$THEME_FILE" ]; then
  source "$THEME_FILE"
else
  source "${CONFIG_DIR:-$HOME/.config/sketchybar}/tokens/themes/onedark.sh"
fi

export SBAR_DEFAULT_ICON_COLOR="${SBAR_DEFAULT_ICON_COLOR:-$COLOR_WHITE}"
export SBAR_DEFAULT_LABEL_COLOR="${SBAR_DEFAULT_LABEL_COLOR:-$COLOR_WHITE}"

export SBAR_COLOR_CLOCK="${SBAR_COLOR_CLOCK:-$COLOR_YELLOW}"
export SBAR_COLOR_WEATHER="${SBAR_COLOR_WEATHER:-$COLOR_CYAN}"
export SBAR_COLOR_CAFFEINATE="${SBAR_COLOR_CAFFEINATE:-$COLOR_GREEN}"
export SBAR_COLOR_CAFFEINATE_ON="${SBAR_COLOR_CAFFEINATE_ON:-$COLOR_RED}"
export SBAR_COLOR_VOLUME="${SBAR_COLOR_VOLUME:-$COLOR_BLUE}"
export SBAR_COLOR_BATTERY="${SBAR_COLOR_BATTERY:-$COLOR_ORANGE}"
export SBAR_COLOR_FRONT_APP="${SBAR_COLOR_FRONT_APP:-$COLOR_GREEN}"
export SBAR_COLOR_AEROSPACE="${SBAR_COLOR_AEROSPACE:-$COLOR_PURPLE}"
export SBAR_COLOR_RESTART="${SBAR_COLOR_RESTART:-$COLOR_RED}"

export SBAR_LABEL_FONT_FAMILY="${SBAR_LABEL_FONT_FAMILY:-SpaceMono Nerd Font Mono}"
export SBAR_LABEL_FONT_STYLE="${SBAR_LABEL_FONT_STYLE:-Bold}"
export SBAR_ICON_FONT_FAMILY="${SBAR_ICON_FONT_FAMILY:-$SBAR_LABEL_FONT_FAMILY}"
export SBAR_ICON_FONT_STYLE="${SBAR_ICON_FONT_STYLE:-$SBAR_LABEL_FONT_STYLE}"

export SBAR_ICON_FONT_SIZE="${SBAR_ICON_FONT_SIZE:-18.0}"
export SBAR_LABEL_FONT_SIZE="${SBAR_LABEL_FONT_SIZE:-12.0}"

export SBAR_APP_ICON_FONT="${SBAR_APP_ICON_FONT:-sketchybar-app-font}"
export SBAR_APP_ICON_FONT_SIZE="${SBAR_APP_ICON_FONT_SIZE:-13.5}"

export SBAR_BAR_HEIGHT=56
export SBAR_BAR_Y_OFFSET="${SBAR_BAR_Y_OFFSET:--10}"
export SBAR_BAR_POSITION="top"

export SBAR_ITEM_BG_HEIGHT="${SBAR_ITEM_BG_HEIGHT:-24}"
export SBAR_ITEM_BG_CORNER_RADIUS="${SBAR_ITEM_BG_CORNER_RADIUS:-4}"
export SBAR_ITEM_BG_BORDER_WIDTH="${SBAR_ITEM_BG_BORDER_WIDTH:-1}"
export SBAR_ITEM_ICON_PADDING_LEFT="${SBAR_ITEM_ICON_PADDING_LEFT:-8}"
export SBAR_ITEM_ICON_PADDING_RIGHT="${SBAR_ITEM_ICON_PADDING_RIGHT:-4}"
export SBAR_ITEM_LABEL_PADDING_LEFT="${SBAR_ITEM_LABEL_PADDING_LEFT:-0}"
export SBAR_ITEM_LABEL_PADDING_RIGHT="${SBAR_ITEM_LABEL_PADDING_RIGHT:-8}"

export SBAR_POPUP_ICON_PADDING_LEFT="${SBAR_POPUP_ICON_PADDING_LEFT:-12}"
export SBAR_POPUP_ICON_PADDING_RIGHT="${SBAR_POPUP_ICON_PADDING_RIGHT:-8}"
export SBAR_POPUP_PADDING_LEFT="${SBAR_POPUP_PADDING_LEFT:-8}"
export SBAR_POPUP_PADDING_RIGHT="${SBAR_POPUP_PADDING_RIGHT:-12}"

export SBAR_ITEM_UPDATE_FREQ_DEFAULT="${SBAR_ITEM_UPDATE_FREQ_DEFAULT:-10}"
export SBAR_ITEM_UPDATE_FREQ_FAST="${SBAR_ITEM_UPDATE_FREQ_FAST:-2}"
export SBAR_ITEM_UPDATE_FREQ_SLOW="${SBAR_ITEM_UPDATE_FREQ_SLOW:-30}"

export SBAR_CLOCK_FORMAT="${SBAR_CLOCK_FORMAT:-MM/DD HH:mm}"
export SBAR_WEATHER_LOCATION="${SBAR_WEATHER_LOCATION:-Seoul}"
export SBAR_BLOCK_BG_COLOR="${SBAR_BLOCK_BG_COLOR:-$COLOR_BG1}"
