# ============================================================================
#
#           _                     _      _          _                     _
#      ___ | |_  __ _  _ __  ___ | |__  (_) _ __   | |_  ___   _ __ ___  | |
#     / __|| __|/ _` || '__|/ __|| '_ \ | || '_ \  | __|/ _ \ | '_ ` _ \ | |
#   _ \__ \| |_| (_| || |   \__ \| | | || || |_) |_| |_| (_) || | | | | || |
#  (_)|___/ \__|\__,_||_|   |___/|_| |_||_|| .__/(_)\__|\___/ |_| |_| |_||_|
#                                          |_|
#
#                           Starship configuration file
# ============================================================================


# ==================== Settings ====================

# Get editor completions
"$schema" = 'https://starship.rs/config-schema.json'

# newline between prompts
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

palette = 'default_colors'

# ==================== Prompt ====================

format = """
$directory\
$git_branch\
$git_status\
$git_state\
\
 $fill \
$status\
$custom\
$hostname\
$cmd_duration\
$time\
\
$line_break\
$character\
"""

# ==================== Modules ====================

# ========== Aesthetic ==========

[fill]
disabled = false
style = 'spacer_color'
symbol = "-"

[character]
disabled = false
# success_symbol = ' [❯](bold green)'
# error_symbol   = ' [❯](bold red)'
success_symbol = ' [->](bold green)'
error_symbol   = ' [->](bold red)'

# ========== Files and Directories ==========

[directory]
disabled = false
truncation_length = 1
truncation_symbol = '../'
style = 'dir_color'
format = "[ $path]($style) "

# ========== Git ==========

# shows branch name
[git_branch]
disabled = false
symbol = '󰊢'
style = 'git_orange'
format = "[-](spacer_color) [$symbol $branch]($style) "

# shows status of the repo (conflict, ahead, behind, etc)
[git_status]
disabled = false

ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇣${ahead_count}⇡${behind_count} '
modified = '!${count} '
untracked = '?${count} '
stashed = '*${count} '
conflicted = '~${count} '
staged = '+${count} '
deleted = '-${count} '

format = """
[$ahead_behind](git_ahead_behind)\
[$stashed](git_stashed)\
[$conflicted](git_conflicted)\
[$staged](git_staged)\
[$deleted](git_deleted)\
[$modified](git_modified)\
[$untracked](git_untracked)\
"""

# shows state of any git operations (rebase, merge, etc)
[git_state]
disabled = false

# ========== Time ==========

[cmd_duration]
disabled = false
style = 'timer_color'
format = "[󰔛 $duration]($style) [-](spacer_color) "

[time]
disabled = false
style = 'clock_color'
time_format = "%I:%M:%S"
format = "[ $time]($style)"

# ========== Conditional Information ==========

[status]
disabled = false
style = 'red'
symbol = ''
format = "[$symbol $common_meaning$signal_name$maybe_int]($style) [-](spacer_color) "

[hostname]
disabled = false
ssh_only = true
trim_at = '.'
style = 'bold yellow'
format = '[󰒋 $hostname]($style) [-](spacer_color) '

[custom.tmux]
command = 'tmux display-message -p "#{session_name}"'
when = 'test -n "$TMUX"'
format = '[ $output]($style) [-](spacer_color) '

# ==================== Colors ====================

[palettes.default_colors]
spacer_color = '#464646'
timer_color = '#ADA81D'
dir_color = '#099EF4'
clock_color = '#1A6DBF'
tmux_color = '#32D74B'

git_orange = '#F05233'
git_modified = 'yellow'
git_untracked = 'blue'
git_ahead_behind = 'green'
git_staged = 'green'
git_unstaged = 'blue'
git_stashed = 'purple'
git_conflicted = 'red'
git_deleted = 'red'
