# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
notARepository: "quit"
git:
  autoFetch: false
  disableForcePushing: true
os:
  editPreset: "nvim"
  editAtLine: "nvim {{filename}} +{{line}}"
gui:
  spinner:
    rate: 100
    frames:
      - ⠋
      - ⠙
      - ⠹
      - ⠸
      - ⠼
      - ⠴
      - ⠦
      - ⠧
      - ⠇
      - ⠏
  theme:
    activeBorderColor:
      - "#f59a64" # orange-normal
      - bold
    inactiveBorderColor:
      - "#a6adc8" # fg-muted
    optionsTextColor:
      - "#7aacf9" # blue-normal
    selectedLineBgColor:
      - "#313244" # surface-sunken
    cherryPickedCommitBgColor:
      - "#45475a" # surface
    cherryPickedCommitFgColor:
      - "#f59a64" # orange-normal
    unstagedChangesColor:
      - "#ee668c" # red-normal
    defaultFgColor:
      - "#cdd6f4" # fg
    searchingActiveBorderColor:
      - "#f0d57c" # yellow-normal
  authorColors:
    "*": "#a29ffb" # lilac-normal
