# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
notARepository: "quit"
git:
  autoFetch: false
  disableForcePushing: true
os:
  editPreset: "nvim"
  editAtLine: "nvim {{filename}} +{{line}}"
gui:
  spinner:
    rate: 100
    frames:
      - ⠋
      - ⠙
      - ⠹
      - ⠸
      - ⠼
      - ⠴
      - ⠦
      - ⠧
      - ⠇
      - ⠏
  theme:
    activeBorderColor:
      - "#fab387"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#fab387"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
