# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
notARepository: "quit"
disableStartupPopups: true
promptToReturnFromSubprocess: false
git:
  autoFetch: false
  disableForcePushing: true
  pagers:
    - pager: "delta --paging=never"
os:
  editPreset: "nvim"
  editAtLine: "nvim {{filename}} +{{line}}"
  openDirInEditor: "nvim {{filename}}"
gui:
  expandFocusedSidePanel: true
  tabWidth: 2
  enlargedSideViewLocation: left
  sidePanelWidth: 0.25
  expandedSidePanelWeight: 3
  showRootItemInFileTree: false
  fileTreeSortOrder: foldersFirst
  showBottomLine: false
  showCommandLog: false
  nerdFontsVersion: "3"
  showDivergenceFromBaseBranch: arrowAndNumber
  border: rounded
  statusPanelView: allBranchesLog
  spinner:
    rate: 100
    frames:
      - ⠋
      - ⠙
      - ⠹
      - ⠸
      - ⠼
      - ⠴
      - ⠦
      - ⠧
      - ⠇
      - ⠏
  theme:
    activeBorderColor:
      - "#f59a64" # orange-normal
      - bold
    inactiveBorderColor:
      - "#a6adc8" # fg-muted
    optionsTextColor:
      - "#7aacf9" # blue-normal
    selectedLineBgColor:
      - "#313244" # surface-sunken
    cherryPickedCommitBgColor:
      - "#45475a" # surface
    cherryPickedCommitFgColor:
      - "#f59a64" # orange-normal
    unstagedChangesColor:
      - "#ee668c" # red-normal
    defaultFgColor:
      - "#cdd6f4" # fg
    searchingActiveBorderColor:
      - "#f0d57c" # yellow-normal
    inactiveViewSelectedLineBgColor:
      - "#585b70" # surface-raised
    markedBaseCommitFgColor:
      - "#c490f0" # purple-normal
    markedBaseCommitBgColor:
      - "#45475a" # surface
  branchColorPatterns:
    "^(main|master)$": "#7aacf9" # blue-normal
    "^develop$": "#6addca" # teal-normal
    "^(feat|feature)/": "#8ae28e" # green-normal
    "^fix/": "#f59a64" # orange-normal
    "^(chore|docs|refactor|test|ci)/": "#c490f0" # purple-normal
  authorColors:
    "*": "#a29ffb" # lilac-normal


# TODO:
# Keybindings.
# Each binding can be a single key or a list of keys; see
# https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Custom_Keybindings.md
# for the syntax
