--- Colorscheme: catppuccin with full palette override from chezmoi colors.toml
--- See ~/dotfiles/docs/colorscheme.md
--- Color values sourced from colorscheme/palette.lua (generated by chezmoi)

local palette = require("colorscheme.palette")

return {
  "typicode/bg.nvim",

  {
    "catppuccin/nvim",
    name = "catppuccin-custom",
    lazy = false,
    priority = 1000, -- load before other plugins
    auto_integrations = true,
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd.colorscheme("catppuccin-mocha")
    end,
    opts = {
      flavour = "mocha",
      no_italic = false,
      term_colors = true,
      transparent_background = true, -- let terminal bg show through
      styles = { -- no extra styling on syntax groups
        comments = {},
        conditionals = {},
        loops = {},
        functions = {},
        keywords = {},
        strings = {},
        variables = {},
        numbers = {},
        booleans = {},
        properties = {},
        types = {},
      },
      color_overrides = {
        mocha = palette.catppuccin,
      },
      highlight_overrides = {
        mocha = function(colors)
          return {
            ["@markup.italic"] = { fg = colors.yellow, style = { "italic" } },
            ["@markup.raw"] = { fg = colors.mauve }, -- inline `code` → purple
            ["@markup.raw.block"] = { fg = colors.mauve }, -- fenced ``` code blocks → purple
            SnacksDashboardHeader = { fg = colors.lavender },
            CursorLineNr = { fg = colors.peach, style = { "bold" } },
            PmenuSel = { bg = colors.surface0, fg = colors.peach, style = { "bold" } },
            CursorLine = { bg = colors.surface0 },
            NormalFloat = { bg = "NONE" }, -- transparent floats
            FloatBorder = { bg = "NONE" },
            FloatTitle = { bg = "NONE" },

            -- gitsigns inline preview overrides for transparent mode
            -- added: explicit fg for consistent readability
            GitSignsAddInline = { fg = colors.text, style = { "bold" } },
            -- changed: amber bg (semantic yellow, not Catppuccin's default blue)
            GitSignsChangeInline = { fg = colors.text, bg = palette.diff.gitsigns_change_bg, style = { "bold" } },
            -- deleted: stronger red bg
            GitSignsDeleteInline = { fg = colors.text, bg = palette.diff.gitsigns_delete_bg, style = { "bold" } },
            -- deleted virtual lines: dim red bg, stronger red on words
            GitSignsDeleteVirtLn = { bg = palette.diff.gitsigns_delete_virt },
            GitSignsDeleteVirtLnInLine = { bg = palette.diff.gitsigns_delete_bg },
            GitSignsVirtLnum = { fg = palette.diff.gitsigns_virt_lnum },

            -- diff mode overrides (mergetool, :diffsplit, etc.)
            DiffAdd = { bg = palette.diff.add_bg },
            DiffChange = { bg = palette.diff.change_bg },
            DiffDelete = { bg = palette.diff.delete_bg },
            DiffText = { fg = colors.peach, bg = colors.surface0 },
            DiffTextAdd = { fg = colors.green, bg = colors.surface0 },
          }
        end,
      },
      integrations = {
        dropbar = { enabled = true, color_mode = true },
        blink_cmp = { enabled = true, style = "bordered" },
        gitsigns = true,
        mason = true,
        noice = true,
        render_markdown = true,
        which_key = true,
        snacks = { enabled = true },
        harpoon = true,
        lualine = { enabled = true },
      },
    },
  },
}
