#!/bin/bash

ACCOUNT="$1"

if [ -z "$ACCOUNT" ]; then
  exit 0
fi

case "$ACCOUNT" in
"proton")
  KEYCHAINKEY="PROTON"
  ;;
"gmail")
  KEYCHAINKEY="Gmail"
  ;;
"outlook")
  python3 ~/.config/aerc/scripts/mutt_oauth2.py ~/.config/aerc/scripts/outlook-token.priv
  exit 0
  ;;
*)
  echo "Unknown Account"
  exit 1
  ;;
esac

security find-generic-password -w -s "$KEYCHAINKEY"
